version: "3.9"
   
services:
  app-db:
    image: postgres
    container_name: app-db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d/
      - ./db/GlobalLandTemperaturesByCity.csv:/GlobalLandTemperaturesByCity.csv
  app:
    build: ./app
    container_name: app
    restart: always
    depends_on:
      - app-db
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URI=postgresql://postgres:password@app-db:5432/postgres
    ports:
      - 5000:5000
networks:
  app-network:
